title: Duval DVL
email: contact@duvaldvl.com
description: >-
  Webdesigner freelance & Expert SEO à Sallanches (74). Création de sites internet
  et référencement local en Haute-Savoie pour booster votre visibilité.
baseurl: "/duvaldvl" # À laisser tel quel pour le test, à vider pour le domaine final
url: "https://duvaldvl.com" # À changer par ton domaine final plus tard
twitter_username: duvaldvl
github_username: duvaldvl
locale: fr_FR
image: /assets/images/social-preview.png

# Configuration SEO
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Données sociales (utilisées dans le footer)
social:
  instagram: https://www.instagram.com/claymentd/
  linkedin: https://www.linkedin.com/in/duvaldvl/
  gmb: https://share.google/CpQnXHAhxj7Y6aMXq # Lien court GMB

  # Contact
contact:
  phone: "07 60 16 61 36"
  email: "duvalrenouveau@gmail.com"
  address: "540 rue Charles Viard, 74700 Sallanches"
